### ISSUE TITLE
Is there any pretrained classification model for CUB?

### ISSUE THREAD

**Issue by xixiobba** [tzzcl/PSOL#6]
My classification accuracy is only 70%  TnT

**Comment by tzzcl** [comment]
Hi, due to the space limit on our GPU server, I've deleted my model for CUB.

But for CUB classification, you can reach to the official ImageNet repo and tweak this repo a little bit, then you can achieve 76%+ acc on VGG16 and 80%+ acc on ResNet50, I do not add other tricks that can make ResNet50 achieves 84 or 85+ acc.
